version: "2.1"

services:
  mongo:
    image: mongo
    container_name: gatekeeper-mongo
    restart: always
    expose:
      - 27017
    depends_on:
      - cache
    volumes:
      - ./data/mongodb/mongod.conf:/etc/mongod.conf
      - ./data/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./data/mongodb/data/db/:/data/db/
      - ./data/mongodb/data/log/:/var/log/mongodb/
    networks:
      - "test_network"

  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile-rabbitmq
    container_name: gatekeeper-rabbitmq
    depends_on:
      - mongo
    expose:
      - 4369
      - 5672
      - 15672
      - 25672
      - 35197
    volumes:
      - ./data/rabbitmq/lib:/var/lib/rabbitmq
      - ./data/rabbitmq/logs:/var/log/rabbitmq
    hostname: rabbit
    networks:
      - "test_network"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 10s
        retries: 5

  cache:
    image: redis
    container_name: gatekeeper-cache
    expose:
      - 6379
    networks:
      - "test_network"

  server:
    build:
      context: ./server
    container_name: gatekeeper-server
    depends_on:
      rabbitmq:
        condition: service_healthy
    tty: true
    stdin_open: true
    expose:
      - 8080
    volumes:
      - './server/config.yaml:/server/config.yaml'
    environment:
      - FRONTEND_DEPLOYED_URL=http://ec2-52-7-62-56.compute-1.amazonaws.com/
    networks:
      - "test_network"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    build:
      context: ./app
    container_name: gatekeeper-nginx
    depends_on:
      - server
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RECAPTCHA_SITEKEY=6Ld7qcAUAAAAADtzQrmz7it_EOpygwqSKuC8nY5I
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - "test_network"
networks:
  test_network: