package server

import (
	"encoding/json"
	"io/ioutil"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/sirupsen/logrus"
	"github.com/tywin1104/mc-whitelist/types"
	"github.com/tywin1104/mc-whitelist/utils"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

func (svc *Service) getRequestByEncryptedID(requestIdEncoded string) (*types.WhitelistRequest, string, int) {
	log := svc.logger
	requestID, err := utils.DecodeAndDecrypt(requestIdEncoded, svc.c.PassPhrase)
	if err != nil {
		log.WithFields(logrus.Fields{
			"err":      err.Error(),
			"urlParam": requestIdEncoded,
		}).Error("Unable to decode requestID token")
		return nil, "Unable to decode token", http.StatusBadRequest
	}

	_id, _ := primitive.ObjectIDFromHex(string(requestID))
	requests, err := svc.dbService.GetRequests(1, bson.D{{"_id", _id}})
	if err != nil {
		log.WithFields(logrus.Fields{
			"err":       err.Error(),
			"requestID": requestID,
		}).Error("Unable to get reqeuest by ID")
		return nil, "Unable to get reqeuest by ID", http.StatusInternalServerError
	}
	if len(requests) == 0 {
		return nil, "Resource not found", http.StatusBadRequest
	}
	request := requests[0]
	return request, "", http.StatusOK

}
func (svc *Service) handleGetRequestByID() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		request, errMsg, statusCode := svc.getRequestByEncryptedID(mux.Vars(r)["requestIdEncoded"])
		if errMsg != "" {
			http.Error(w, errMsg, statusCode)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		// For external facing get request, only display non-sensitive necessary fields
		msg := map[string]map[string]interface{}{"request": {
			"username":  request.Username,
			"email":     request.Email,
			"status":    request.Status,
			"timestamp": request.Timestamp,
			"info":      request.Info,
		}}
		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(msg)
	}
}

func (svc *Service) handleCreateRequest() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		log := svc.logger
		// Validating request body
		var newRequest types.WhitelistRequest
		reqBody, err := ioutil.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "Unable to read request body", http.StatusBadRequest)
			return
		}
		err = json.Unmarshal(reqBody, &newRequest)
		if err != nil {
			http.Error(w, "Unable to unmarshal request body", http.StatusInternalServerError)
			return
		}

		// Prevent new request from a approved or pending username
		foundRequests, err := svc.dbService.GetRequests(-1, bson.M{
			"username": newRequest.Username,
			"status":   bson.M{"$in": []string{"Pending", "Approved"}},
		})
		if err != nil {
			http.Error(w, "Unable to check user's record", http.StatusInternalServerError)
			return
		}
		if len(foundRequests) > 0 {
			w.WriteHeader(http.StatusBadRequest)
			var message string
			if foundRequests[0].Status == "Approved" {
				message = "The request associated with this username is already approved"
			} else {
				message = "There is a pending request associated with this username. " +
					"You can not submit another request at this time. If you haven't received " +
					"result within 24 hours, please contact admin"
			}
			msg := map[string]interface{}{"message": message}
			json.NewEncoder(w).Encode(msg)
			return
		}
		// Add corresponding whitelist request to the database
		newRequestID, err := svc.dbService.CreateRequest(newRequest)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			log.WithFields(logrus.Fields{
				"err": err.Error(),
			}).Error("Unable to create new request")
			return
		}
		// Add corresponding whitelist request to the queue for worker to fetch and handle
		// Need to append its object ID that is being generated by DB service here
		newRequest.ID = newRequestID
		newRequest.Status = "Pending"
		err = svc.broker.Publish(newRequest)
		if err != nil {
			log.WithFields(logrus.Fields{
				"error":      err,
				"newRequest": newRequest,
			}).Error("Unable to publish message to broker")
		}

		w.WriteHeader(http.StatusOK)
		msg := map[string]interface{}{"message": "success", "created": newRequestID}
		json.NewEncoder(w).Encode(msg)
	}
}

func (svc *Service) handlePatchRequestByID() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		log := svc.logger
		requestID, err := utils.DecodeAndDecrypt(mux.Vars(r)["requestIdEncoded"], svc.c.PassPhrase)
		if err != nil {
			log.WithFields(logrus.Fields{
				"err":      err.Error(),
				"urlParam": mux.Vars(r)["requestIdEncoded"],
			}).Error("Unable to decode requestID token")
			http.Error(w, "Unable to decode token", http.StatusBadRequest)
			return
		}
		// Get admin info from ?adm=<EncodedAdminEmail>
		keys, ok := r.URL.Query()["adm"]

		if !ok || len(keys[0]) < 1 {
			http.Error(w, "adm token is missing", http.StatusBadRequest)
			return
		}
		admToken := keys[0]
		opEmail, err := utils.DecodeAndDecrypt(admToken, svc.c.PassPhrase)
		if err != nil {
			log.WithFields(logrus.Fields{
				"err":      err.Error(),
				"urlParam": mux.Vars(r)["requestIdEncoded"],
			}).Error("Unable to decode adm token")
			http.Error(w, "Unable to decode token", http.StatusBadRequest)
			return
		}

		_id, _ := primitive.ObjectIDFromHex(requestID)
		var requestedChange bson.M
		reqBody, err := ioutil.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "Unable to read request body", http.StatusBadRequest)
			return
		}
		// Only update a request if its status is still pending
		foundRequests, err := svc.dbService.GetRequests(-1, bson.M{
			"_id":    _id,
			"status": "Pending",
		})
		if err != nil {
			http.Error(w, "Unable to check user's record", http.StatusInternalServerError)
			return
		}
		if len(foundRequests) > 0 {
			json.Unmarshal(reqBody, &requestedChange)
			// Going to update the admin field of the request to whoever perform the action through UI
			requestedChange["admin"] = opEmail
			// Parse timestamp string into time type
			processedTimestamp, err := parseTimestamp(requestedChange["processedTimestamp"])
			requestedChange["processedTimestamp"] = processedTimestamp
			updatedRequest, err := svc.dbService.UpdateRequest(bson.D{{"_id", _id}}, bson.M{
				"$set": requestedChange,
			})
			if err != nil {
				http.Error(w, "Unable to update request", http.StatusInternalServerError)
				log.WithFields(logrus.Fields{
					"err":             err.Error(),
					"requestID":       requestID,
					"requestedChange": requestedChange,
				}).Error("Unable to update request")
				return
			}
			// Add task to broker so that user will receive status update email
			// convert bson.M to struct
			var updatedRequestObj types.WhitelistRequest
			bsonBytes, _ := bson.Marshal(updatedRequest)
			bson.Unmarshal(bsonBytes, &updatedRequestObj)

			// Publish the updatedRequestObj to broker
			err = svc.broker.Publish(updatedRequestObj)
			if err != nil {
				log.WithFields(logrus.Fields{
					"error":             err,
					"updatedReqeustObj": updatedRequestObj,
				}).Error("Unable to publish message to broker")
			}
			w.Header().Set("Content-Type", "application/json")
			msg := map[string]interface{}{"message": "success", "updated": updatedRequestObj}
			w.WriteHeader(http.StatusOK)
			json.NewEncoder(w).Encode(msg)
		} else {
			msg := map[string]interface{}{"message": "Invalid requestId or the target request is already closed"}
			w.WriteHeader(http.StatusBadRequest)
			json.NewEncoder(w).Encode(msg)
		}
	}
}
